import { create } from "zustand";
import { persist } from "zustand/middleware";

import { idbStorage } from "@/shared/storage/idb-storage";
import type { LearningEvent, LearningEventType } from "@/shared/types";

/**
 * Input shape for recording a new learning event.
 * id, timestamp, and synced are auto-generated by the store.
 */
export type EventInput = {
  type: LearningEventType;
  payload: LearningEvent["payload"];
};

type EventsState = {
  events: LearningEvent[];
  isLoading: boolean;
  error: string | null;
};

type EventsActions = {
  loadEvents: (limit?: number) => Promise<void>;
  recordEvent: (input: EventInput) => Promise<void>;
  getUnsyncedEvents: () => LearningEvent[];
  markSynced: (ids: string[]) => Promise<void>;
  getEventsByType: (type: LearningEventType, limit?: number) => LearningEvent[];
  clearAll: () => Promise<void>;
  refresh: (limit?: number) => Promise<void>;
};

type EventsStore = EventsState & EventsActions;

const MAX_EVENTS = 50;

export const useEventsStore = create<EventsStore>()(
  persist(
    (set, get) => ({
      events: [],
      isLoading: true,
      error: null,

      loadEvents: async (limit = MAX_EVENTS) => {
        // Zustand `persist` middleware hydrates the store from IDB on init.
        // This action is kept for API compatibility but only normalizes
        // loading state — the events array is already in memory.
        void limit;
        set({ isLoading: false, error: null });
      },

      recordEvent: async (input: EventInput) => {
        const event: LearningEvent = {
          id: crypto.randomUUID(),
          type: input.type,
          timestamp: Date.now(),
          payload: input.payload,
          synced: false,
        } as LearningEvent;

        set((state) => ({
          events: [event, ...state.events].slice(0, MAX_EVENTS),
          error: null,
        }));
      },

      getUnsyncedEvents: () => {
        return get().events.filter((e) => !e.synced);
      },

      markSynced: async (ids: string[]) => {
        set((state) => ({
          events: state.events.map((e) =>
            ids.includes(e.id) ? { ...e, synced: true } : e,
          ),
          error: null,
        }));
      },

      getEventsByType: (type: LearningEventType, limit?: number) => {
        const filtered = get().events.filter((e) => e.type === type);
        return limit ? filtered.slice(0, limit) : filtered;
      },

      clearAll: async () => {
        set({ events: [], error: null });
      },

      refresh: async (limit?: number) => {
        return get().loadEvents(limit);
      },
    }),
    {
      name: "events-state",
      storage: idbStorage("learning_events"),
      partialize: (state) => ({ events: state.events }),
    },
  ),
);
